
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  pokemon:  # id of input
    description: 'pokemon from commit'
    required: true
    default: 'pikachu'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pokemon }}
