on: [push]

jobs:
  pokemon:
    runs-on: ubuntu-latest
    name: get pokemon
    steps:
      - name: Hello world action step
        id: hello
        uses: jesheep99/Readmedex@v1.06
        with:
          pokemon: ${{ github.event.head_commit.message }}
      # Use the output from the `hello` step
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Readme.md
          path: Readme.md
