on: [push]

jobs:
  pokemon:
    runs-on: ubuntu-latest
    name: get pokemon
    steps:
      - name: Hello world action step
        id: hello
        uses: jesheep99/Readmedex@v1.06
        with:
          pokemon: ${{ github.event.head_commit.message }}
      - name: Update README.md
        run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto-update README.md"
          git push
        fi
